[2025-10-27T05:11:41.657+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T05:11:41.696+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_minio_to_snowflake_bronze.load_raw_to_snowflake scheduled__2025-10-27T04:00:00+00:00 [queued]>
[2025-10-27T05:11:41.709+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_minio_to_snowflake_bronze.load_raw_to_snowflake scheduled__2025-10-27T04:00:00+00:00 [queued]>
[2025-10-27T05:11:41.711+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-27T05:11:41.725+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_raw_to_snowflake> on 2025-10-27 04:00:00+00:00
[2025-10-27T05:11:41.736+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_minio_to_snowflake_bronze', 'load_raw_to_snowflake', 'scheduled__2025-10-27T04:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/minio-to-kafka.py', '--cfg-path', '/tmp/tmpxighj3y_']
[2025-10-27T05:11:41.743+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_raw_to_snowflake
[2025-10-27T05:11:41.744+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=468) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-27T05:11:41.745+0000] {standard_task_runner.py:64} INFO - Started process 478 to run task
[2025-10-27T05:11:41.850+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_minio_to_snowflake_bronze.load_raw_to_snowflake scheduled__2025-10-27T04:00:00+00:00 [running]> on host 681395a7d9e3
[2025-10-27T05:11:41.977+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_minio_to_snowflake_bronze' AIRFLOW_CTX_TASK_ID='load_raw_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T04:00:00+00:00'
[2025-10-27T05:11:41.981+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T05:11:42.015+0000] {connection.py:408} INFO - Snowflake Connector for Python Version: 3.11.0, Python Version: 3.12.4, Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-10-27T05:11:42.017+0000] {connection.py:1258} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-27T05:11:43.003+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T05:11:43.004+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/minio-to-kafka.py", line 115, in load_raw_to_snowflake
    cur.execute(f"USE DATABASE {SNOWFLAKE_DATABASE}")
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002043 (02000): 01bffbb7-0001-5618-0000-000b0d4a6061: SQL compilation error:
Object does not exist, or operation cannot be performed.
[2025-10-27T05:11:43.022+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spotify_minio_to_snowflake_bronze, task_id=load_raw_to_snowflake, run_id=scheduled__2025-10-27T04:00:00+00:00, execution_date=20251027T040000, start_date=20251027T051141, end_date=20251027T051143
[2025-10-27T05:11:43.039+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task load_raw_to_snowflake (002043 (02000): 01bffbb7-0001-5618-0000-000b0d4a6061: SQL compilation error:
Object does not exist, or operation cannot be performed.; 478)
[2025-10-27T05:11:43.086+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-27T05:11:43.113+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T05:11:43.116+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
